website-revamp/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :portfolio, only: [:index, :show]
  resources :blog, only: [:index, :show]
  get 'resume', to: 'resume#show'
end

website-revamp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website-revamp/app/controllers/blog_controller.rb
class BlogController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website-revamp/app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website-revamp/app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website-revamp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website-revamp/app/helpers/application_helper.rb
module ApplicationHelper
end

website-revamp/app/views/blog/index.html.erb
<div class="container">
  <div id="blog-index">
    <h3>Blog Index</h3>
  </div>
</div>

website-revamp/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'home', root_path %><li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

            <li class="page-scroll">
                <%= link_to 'portfolio', portfolio_index_path %> |
            </li>
            <li class="page-scroll">
                <%= link_to 'blog', blog_index_path %> |
            </li>
            <li class="page-scroll">
                  <%= link_to 'resume', resume_path %>
            </li>
        </ul>
    </div>
  </div>
</nav>

website-revamp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>dionneStanfield</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700|Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

</head>
<body id="page-top" class="index">
  <%= render 'layouts/navigation' %>
  <header>
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <img class="img-responsive" src="img/profile.png" alt="">
            <div class="intro-text">
                <span class="name">Dionne Stanfield</span>
                <hr class="star-light">
                <span class="skills">Jr. Web Developer - Sr. Web Surfer - User Experience Designer</span>
            </div>
        </div>
    </div>
    </div>
  </header>
  <%= yield %>


</body>
</html>

website-revamp/app/views/portfolio/index.html.erb
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Portfolio</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 portfolio-item">
                <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="img/portfolio/cabin.png" class="img-responsive" alt="">
                </a>
            </div>
            <div class="col-sm-4 portfolio-item">
                <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="img/portfolio/cake.png" class="img-responsive" alt="">
                </a>
            </div>
            <div class="col-sm-4 portfolio-item">
                <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="img/portfolio/circus.png" class="img-responsive" alt="">
                </a>
            </div>
            <div class="col-sm-4 portfolio-item">
                <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="img/portfolio/game.png" class="img-responsive" alt="">
                </a>
            </div>
            <div class="col-sm-4 portfolio-item">
                <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="img/portfolio/safe.png" class="img-responsive" alt="">
                </a>
            </div>
            <div class="col-sm-4 portfolio-item">
                <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="img/portfolio/submarine.png" class="img-responsive" alt="">
                </a>
            </div>
        </div>
    </div>
</section>

website-revamp/app/views/resume/show.html.erb
<div class="container">
  <div class="resume-container">
    <h3>Resume will live here.</h3>
  <div>
</div>

website-revamp/app/views/welcome/index.html.erb
<!-- Portfolio Grid Section -->
<section id="portfolio">
  <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2>Portfolio</h2>
              <hr class="star-primary">
          </div>
      </div>
      <div class="row">
          <div class="col-sm-4 portfolio-item">
              <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                  <div class="caption">
                      <div class="caption-content">
                          <i class="fa fa-search-plus fa-3x"></i>
                      </div>
                  </div>
                  <img src="img/portfolio/cabin.png" class="img-responsive" alt="">
              </a>
          </div>
          <div class="col-sm-4 portfolio-item">
              <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                  <div class="caption">
                      <div class="caption-content">
                          <i class="fa fa-search-plus fa-3x"></i>
                      </div>
                  </div>
                  <img src="img/portfolio/cake.png" class="img-responsive" alt="">
              </a>
          </div>
          <div class="col-sm-4 portfolio-item">
              <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                  <div class="caption">
                      <div class="caption-content">
                          <i class="fa fa-search-plus fa-3x"></i>
                      </div>
                  </div>
                  <img src="img/portfolio/circus.png" class="img-responsive" alt="">
              </a>
          </div>
          <div class="col-sm-4 portfolio-item">
              <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                  <div class="caption">
                      <div class="caption-content">
                          <i class="fa fa-search-plus fa-3x"></i>
                      </div>
                  </div>
                  <img src="img/portfolio/game.png" class="img-responsive" alt="">
              </a>
          </div>
          <div class="col-sm-4 portfolio-item">
              <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                  <div class="caption">
                      <div class="caption-content">
                          <i class="fa fa-search-plus fa-3x"></i>
                      </div>
                  </div>
                  <img src="img/portfolio/safe.png" class="img-responsive" alt="">
              </a>
          </div>
          <div class="col-sm-4 portfolio-item">
              <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                  <div class="caption">
                      <div class="caption-content">
                          <i class="fa fa-search-plus fa-3x"></i>
                      </div>
                  </div>
                  <img src="img/portfolio/submarine.png" class="img-responsive" alt="">
              </a>
          </div>
      </div>
  </div>
</section>

<!-- About Section -->
<section class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-light">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <p>I am a jr. web-developer and former attorney.  I don't take cases anymore, but if you buy me a beer, I'll regale you with war stories from my days in criminal defense.</p>
            </div>
            <div class="col-lg-4">
                <p>Currently, I'm working on a number of solo projects on Rails and in JavaScript.</p>
            </div>
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <a href="#" class="btn btn-lg btn-outline"> see my resume </a>
            </div>
        </div>
    </div>
</section>

<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Contact Me</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-success btn-lg">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>Philadelphia, PA</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="https://github.com/SputterPuttRedux" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
                        </li>
                        <li>
                            <a href="https://plus.google.com/+DionneStanfield/posts" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="https://twitter.com/dionnestanfield" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/dionnestanfield" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">

                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Your Website 2014
                </div>
            </div>
        </div>
    </div>
</footer>